version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: realTimeCommentSystemSecond
    environment:
      POSTGRES_USER: commentUser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: commentSystemDatabaseSecond
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: